name: VillagersDelight
version: '0.1.0'
main: com.huidu.villagersdelight.core.VillagersDelightPlugin
authors:
  - HuiDu_OwO
api-version: '1.21'
depend:
  - CraftEngine
softdepend:
  - FarmersDelight
  - CustomCrops
folia-supported: true
commands:
  villagersdelight:
    description: VillagersDelight 管理命令
    usage: /villagersdelight reload | /villagersdelight inv
    aliases: [ vd ]
    permission: villagersdelight.reload
permissions:
  villagersdelight.reload:
    description: 重载 VillagersDelight 配置
    default: op
